### ISSUE TITLE
usage with singularity/ docker without root/sudo permission?

### ISSUE THREAD

**Issue by matt-shenton** [grimmlab/permGWAS#8]
Hi there, I managed to analyse the test data on my local machine using docker and singularity.

for singularity, unless  I used sudo to run the container, there were not appropriate permissions to write the results files.

here's what I did:
`docker build -t permgwasimage .

docker run -it -v /home/mshenton/permGWAS:/home/permgwascontainer --name permgwascontainer permgwasimage
`
i can successfully run gwas

`
docker save permgwasimage -o localpermgwas2.tar
singularity build localpermgwas2.sif docker-archive://localpermgwas2.tar

singularity shell --bind /home/mshenton/permGWAS:/home/permgwascontainer localpermgwas2.sif
`
`
Done performing GWAS on phenotype phenotype_value for 194 samples and 2001 SNPs.
Elapsed time: 0.993591 s
Save results.
Failure when running permGWAS2.0
[Errno 13] Permission denied: '/home/permgwascontainer3/results/p_values_phenotype_value(3).csv'
`

`
sudo singularity shell --bind /home/mshenton/permGWAS:/home/permgwascontainer localpermgwas2.sif

`
With sudo, I can successfully run gwas. However, I'd like to use this on a server where I don't have sudo priveleges. I can't use Docker there either. Any suggestions? 

Thanks for the tool!

bets regards
Matt

**Comment by MauraJohn** [comment]
Hi Matt,

as far as I know, you don't need sudo rights for singularity. I think the problem is with your results directory. Seems like you don't have the rights to write in this folder. To check this, you could try to move a file into this directory without using permGWAS. You could also just create a new results directory in your singularity shell and use this to save your output files.

Best regards,
Maura

**Comment by matt-shenton** [comment]
Thanks a lot. I'm not sure why, but I couldn't write to the "results" directory inside the container. Specifying an absolute path to a different location did the job.

Best regards
Matt
